
use org;
DELIMITER &&
CREATE FUNCTION computeTax(salary int)RETURNS DECIMAL(10,2) DETERMINISTIC BEGIN
DECLARE incomeTax DECIMAL(10,2);
IF salary<=75000 THEN SET incomeTax=0.1*salary; 
ELSEIF salary>75000 and salary<=150000 THEN SET incomeTax=0.2*salary;
ELSE SET incomeTax=0.3*SALARY;
END IF;
RETURN incomeTax;
END &&
DELIMITER ;
SELECT * ,computeTax(salary)FROM WORKER;





DELIMITER &&
CREATE PROCEDURE CALCULATEINCOMETAX(IN SALARY INT,OUT INCOMETAX DECIMAL(10,2))
BEGIN
SET INCOMETAX=computeTax(SALARY);
END &&
DELIMITER ;
CALL CALCULATEINCOMETAX(80000,@INCOMETAX);
SELECT @INCOMETAX;

